### ISSUE TITLE
gitlab-ci examples

### ISSUE THREAD

**Issue by wangbo4020** [FIRHQ/fir-cli#262]
请教一下，使用 gitlab-ci 应该怎么配置 deploy 来发布到firim
有个例子将非常感谢

```
image: flutter-android:latest

before_script:
  - chmod +x ./gradlew

assemble:
  stage: build
  tags:
    - android
  only:
    - tags
  script:
    - ./gradlew assembleDebug
  artifacts:
    name: "$CI_PROJECT_NAME_$CI_COMMIT_TAG"
    paths:
      - app/build/outputs/*.apk

deploy:
  stage: deploy
  image:
    name: firhq/fir-cli
    entrypoint:
      - fir publish app/build/outputs -T "api_token"
  script: 
        ...
```
